spring:


  profiles:
    active: native
  application:
    name: room-register-service

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  data:
    mongodb:
      host: localhost
      port: 27017
      database: interview_room
      auto-index-creation: true



  config:
    import:
      - optional:configserver:http://localhost:8888

  jpa:
    show-sql: true
    defer-datasource-initialization: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        hbm2ddl:
          auto: update


