
spring:

  profiles:
    active: native
  application:
    name: JobCreator


  datasource:
    url: jdbc:mysql://localhost:3306/interview_data
    username: root
    password: "123456789"


  config:
    import:
      - optional:configserver:http://localhost:8888

  jpa:
    show-sql: true
    defer-datasource-initialization: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        hbm2ddl:
          auto: update


